---
#===========================================================================
# Get the Infrastructure Provider for this host
#===========================================================================

- name: Get the infrastructure provider for this host
  ansible.builtin.include_tasks: "target_infra_credential.yaml"

#===========================================================================
# Get the Redfish Variables for this host's Infrastructure Provider
#===========================================================================

- name: Get the infrastructure provider for this host
  ansible.builtin.include_tasks: "setup-redfish-vars.yaml"

- name: Shutdown the host if it is powered on
  ansible.builtin.include_tasks: set_power_state_off.yaml

- name: Attach the virtual media
  ansible.builtin.include_tasks: set_virtual_media.yaml

- name: Power on the host
  ansible.builtin.include_tasks: set_power_state_on.yaml
