---

- name: Delete the server file
  ansible.builtin.file:
    path: "{{ generated_asset_directory }}/{{ cluster_id }}/server.py"
    state: absent

- name: Create web server python script
  ansible.builtin.lineinfile:
    create: true
    dest: "{{ generated_asset_directory }}/{{ cluster_id }}/server.py"
    mode: 0755
    line: |
      import os
      from http.server import HTTPServer, CGIHTTPRequestHandler
      # Make sure the server is created at current directory
      os.chdir('.')
      # Create server object listening the port {{ http_server_port | default('7654') }}
      server_object = HTTPServer(server_address=('', {{ http_server_port | default('7654') }}), RequestHandlerClass=CGIHTTPRequestHandler)
      # Start the web server
      server_object.serve_forever()

- name: Scan any process using this port
  ansible.builtin.shell: |
    lsof -n -i :{{ http_server_port | default('7654') }} | grep LISTEN | cut -f 2 -d " "
  register: port_scan
  become: true

- name: Kill any process using this port
  when: port_scan.stdout_lines|length > 0
  ansible.builtin.shell: "kill {{ port_scan.stdout }}"
  become: true

- name: Execute python script
  ansible.builtin.shell: |
    cd {{ generated_asset_directory }}/{{ cluster_id }}
    python3 server.py &> /dev/null &
    echo $!
  register: python_script_out
