---
# tasks file for ocp4-matrix-login
- name: Apply the Login Screen HTML Template
  kubernetes.core.k8s:
    kubeconfig: "{{ generated_asset_directory }}/{{ cluster_id }}/kubeconfig"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Generic
      metadata:
        name: matrix-login-template
        namespace: openshift-config
      data:
        login.html: "{{ lookup('template', 'templates/login.html.j2') | b64encode }}"
  register: matrix_login_template
  retries: 30
  delay: 10
  until: matrix_login_template is succeeded

- name: Patch the OAuth Config
  kubernetes.core.k8s:
    kubeconfig: "{{ generated_asset_directory }}/{{ cluster_id }}/kubeconfig"
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        templates:
          login:
            name: matrix-login-template
  register: oauth_config
  retries: 30
  delay: 10
  until: oauth_config is succeeded
