---
- name: Disable project self-provisioning
  # https://docs.openshift.com/container-platform/4.10/applications/projects/configuring-project-creation.html#disabling-project-self-provisioning_configuring-project-creation
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: self-provisioners
        annotations:
          rbac.authorization.kubernetes.io/autoupdate: 'true'
      subjects: null
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: self-provisioner
  when: disable_project_creation == 'true'
