---
cluster_nodes:
  - name: taco-one
    type: converged
    infra:
      name: labVMWare
      # type: vsphere | nutanix | libvirt | baremetal
      type: vsphere
    vm:
      cpu_cores: 12
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
      disks:
        - size: 240
          name: boot
    networking:
      interfaces:
        - name: eth0
          mac_address: 54:52:00:42:66:21
          dhcp: false
          ipv4:
            - address: 192.168.70.21
              prefix: 23
      routes:
        - destination: 0.0.0.0/0
          next_hop_address: 192.168.70.1
          next_hop_interface: eth0
          table_id: 254

  - name: taco-two
    type: converged
    infra:
      name: labVMWare
      # type: vsphere | nutanix | libvirt | baremetal
      type: vsphere
    vm:
      cpu_cores: 12
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
      disks:
        - size: 240
          name: boot
    networking:
      interfaces:
        - name: eth0
          mac_address: 54:52:00:42:66:22
          dhcp: false
          ipv4:
            - address: 192.168.70.22
              prefix: 23
      routes:
        - destination: 0.0.0.0/0
          next_hop_address: 192.168.70.1
          next_hop_interface: eth0
          table_id: 254

  - name: taco-three
    type: converged
    infra:
      name: labVMWare
      # type: vsphere | nutanix | libvirt | baremetal
      type: vsphere
    vm:
      cpu_cores: 12
      cpu_sockets: 1
      cpu_threads: 1
      memory: 32768
      disks:
        - size: 240
          name: boot
    networking:
      interfaces:
        - name: eth0
          mac_address: 54:52:00:42:66:23
          dhcp: false
          ipv4:
            - address: 192.168.70.23
              prefix: 23
      routes:
        - destination: 0.0.0.0/0
          next_hop_address: 192.168.70.1
          next_hop_interface: eth0
          table_id: 254
