---
# ===========================================================================
# Get the Redfish Variables for this Infrastructure Provider
# ===========================================================================

- name: Get the infrastructure provider for this host
  ansible.builtin.include_tasks: "tasks/infra-baremetal/setup-redfish-vars.yaml"

- name: d
  ansible.builtin.debug:
    msg:
      - "{{ redfish_systems_url }}"
      - "{{ redfish_managers_url }}"
