---

####################################################### CLUSTER INFO

- name: Get available clusters
  uri:
    url: "https://{{ provider.credentials.prism_endpoint }}:9440{{ nutanix_prism_api_v3_base }}/clusters/list"
    return_content: yes
    method: POST
    status_code: 200
    body_format: json
    body: '{"kind":"cluster", "filter": "name=={{ provider.configuration.prism_cluster_name }}"}'
    force_basic_auth: yes
    user: "{{ provider.credentials.prism_username }}"
    password: "{{ provider.credentials.prism_password }}"
    validate_certs: "{{provider.credentials.prism_verify_ssl }}"
  register: nutanix_clusters_info

- name: Set Facts - Set Cluster UUID
  when: cluster.spec.name == provider.configuration.prism_cluster_name
  set_fact:
    nutanix_cluster_uuid: "{{ cluster.metadata.uuid }}"
  loop: "{{ nutanix_clusters_info.json.entities }}"
  loop_control:
    loop_var: cluster
    label: "{{ cluster.spec.name }}"

####################################################### NETWORK INFO

- name: Get available Networks
  uri:
    url: "https://{{ provider.credentials.prism_endpoint }}:9440{{ nutanix_prism_api_v3_base }}/subnets/list"
    return_content: yes
    method: POST
    status_code: 200
    body_format: json
    body: '{"kind":"subnet", "filter": "name=={{ provider.configuration.prism_network_name }}"}'
    force_basic_auth: yes
    user: "{{ provider.credentials.prism_username }}"
    password: "{{ provider.credentials.prism_password }}"
    validate_certs: "{{provider.credentials.prism_verify_ssl }}"
  register: nutanix_networks_info

- name: Set Facts - Set Network UUID
  when: network.spec.name == provider.configuration.prism_network_name
  set_fact:
    nutanix_network_uuid: "{{ network.metadata.uuid }}"
  loop: "{{ nutanix_networks_info.json.entities }}"
  loop_control:
    loop_var: network
    label: "{{ network.spec.name }}"

####################################################### Image INFO

- name: Get available Storage Containers
  uri:
    url: "https://{{ provider.credentials.prism_endpoint }}:9440{{ nutanix_prism_api_v2_base }}/storage_containers"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
    body: '{"filter_criteria": "name=={{ provider.configuration.prism_image_storage_container_name }}"}'
    force_basic_auth: yes
    user: "{{ provider.credentials.prism_username }}"
    password: "{{ provider.credentials.prism_password }}"
    validate_certs: "{{provider.credentials.prism_verify_ssl }}"
  register: nutanix_image_storage_info

- name: Set Facts - Set Cluster Image Storage Container
  when: storage_container.name == provider.configuration.prism_image_storage_container_name
  set_fact:
    nutanix_image_storage_container_uuid: "{{ storage_container.storage_container_uuid }}"
  loop: "{{ nutanix_image_storage_info.json.entities }}"
  loop_control:
    loop_var: storage_container
    label: "{{ storage_container.name }}"

####################################################### VM STORAGE INFO

- name: Get available Storage Containers
  uri:
    url: "https://{{ provider.credentials.prism_endpoint }}:9440{{ nutanix_prism_api_v2_base }}/storage_containers"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
    body: '{"filter_criteria": "name=={{ provider.configuration.prism_vm_storage_container_name }}"}'
    force_basic_auth: yes
    user: "{{ provider.credentials.prism_username }}"
    password: "{{ provider.credentials.prism_password }}"
    validate_certs: "{{provider.credentials.prism_verify_ssl }}"
  register: nutanix_vm_storage_info

- name: Set Facts - Set Cluster VM Storage Container
  when: storage_container.name == provider.configuration.prism_vm_storage_container_name
  set_fact:
    nutanix_vm_storage_container_uuid: "{{ storage_container.storage_container_uuid }}"
  loop: "{{ nutanix_vm_storage_info.json.entities }}"
  loop_control:
    loop_var: storage_container
    label: "{{ storage_container.name }}"

- name: Facts presented
  debug:
    msg:
      - "Cluster UUID: {{ nutanix_cluster_uuid }}"
      - "Network UUID: {{ nutanix_network_uuid }}"
      - "Image Storage Container UUID: {{ nutanix_image_storage_container_uuid }}"
      - "VM Storage Container UUID: {{ nutanix_vm_storage_container_uuid }}"
