---

- name: Query vCenter for a connectivity test
  community.vmware.vmware_datacenter_info:
    hostname: '{{ provider.credentials.vcenter_hostname }}'
    username: '{{ provider.credentials.vcenter_username }}'
    password: '{{ provider.credentials.vcenter_password }}'
    validate_certs: '{{ provider.credentials.vcenter_verify_ssl }}'
  register: vcenter_test_info

- name: Fail if the vCenter instance cannot be connected to
  when: vcenter_test_info.datacenter_info | length == 0
  ansible.builtin.fail:
    msg: "Cannot connect to vCenter at {{ provider.credentials.vcenter_hostname }}!"

- name: Reset facts
  ansible.builtin.set_fact:
    vcenter_test_info: {}
