---

- name: Check for programs - govc
  ansible.builtin.shell: "which govc"
  register: program_check_govc
  ignore_errors: true

- name: Download the govc program if is not found
  when: program_check_govc.rc != 0
  block:
    - name: Download govc
      get_url:
        url: "https://github.com/vmware/govmomi/releases/download/{{ govc_version }}/govc_Linux_x86_64.tar.gz"
        dest: "{{ generated_asset_directory }}/downloads/govc.gz"
        validate_certs: no

    - name: Unarchive govc
      unarchive:
        src: "{{ generated_asset_directory }}/downloads/govc.gz"
        dest: "{{ generated_asset_directory }}/bin/"
        mode: 0755
        exclude:
          - CHANGELOG.md
          - LICENSE.txt
          - README.md

- name: Query vCenter for a connectivity test
  community.vmware.vmware_datacenter_info:
    hostname: '{{ provider.credentials.vcenter_hostname }}'
    username: '{{ provider.credentials.vcenter_username }}'
    password: '{{ provider.credentials.vcenter_password }}'
    validate_certs: '{{ provider.credentials.vcenter_verify_ssl }}'
  register: vcenter_test_info

- name: Fail if the vCenter instance cannot be connected to
  when: vcenter_test_info.datacenter_info | length == 0
  fail:
    msg: "Cannot connect to vCenter at {{ provider.credentials.vcenter_hostname }}!"

- name: Reset facts
  set_fact:
    vcenter_test_info: {}