---
# These tasks will provide an additional logic layer to the processing of the Playbooks

# Mostly this is to make SNO easier - you could also replicate this logic in another
# playbook if you wanted to chain it before/after the main playbook in a Workflow Job

- name: Set the needed SNO fact overrides
  when: cluster_type == "SNO"
  ansible.builtin.set_fact:
    cluster_user_managed_networking: "true"
    schedulable_masters: "true"

- name: Set the needed Compact/Converged Cluster fact overrides
  when: cluster_type in ["Compact", "Converged"]
  ansible.builtin.set_fact:
    schedulable_masters: "true"
