---
- name: Set the wrapped fact
  ansible.builtin.set_fact:
    wrapped_fact: "{{ install_config_overrides | to_json }}"
    installconfigfilepath: "{{ generated_asset_directory }}/{{ cluster_id }}/install-config-overrides"

- name: Take the compiled install-config overrides and write them to a file
  ansible.builtin.copy:
    content: '{{ wrapped_fact | to_json }}'
    dest: "{{ installconfigfilepath }}"
    mode: 0644

- name: Inject install-config overrides into the cluster
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/clusters/{{ cluster_id }}/install-config"
    return_content: true
    method: PATCH
    body: '{{ wrapped_fact | to_json }}'
    status_code: 201
    body_format: json
  register: additional_bundle_ic_resp
  failed_when:
    - additional_bundle_ic_resp.status != 201
    - '"error while adding Platfom baremetal to install config" not in (additional_bundle_ic_resp.content|from_json).reason'
