---

- name: Get the current Discovery Ignition Config overrides
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
  register: infraenv_query

- name: Set fact for Password
  set_fact:
    passwordHash: "{{ core_user_password | password_hash('sha512') }}"
  no_log: true

- name: Get the original Discovery Ignition Config
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}/downloads/files?file_name=discovery.ign"
    return_content: yes
    method: GET
    status_code: 200
    body_format: json
  register: infraenv_discovery_ign_query

- name: Set fact for json content
  set_fact:
    ignition_json: "{{ infraenv_discovery_ign_query.content | from_json }}"
    ignition_overrides: "{{ infraenv_query.json.ignition_config_override | from_json }}"
    passwd_object:
      passwd:
        users:
          - name: core
            groups:
              - sudo
              - wheel
            sshAuthorizedKeys: "{{ (infraenv_discovery_ign_query.content | from_json).passwd.users[0].sshAuthorizedKeys }}"
            passwordHash: "{{ passwordHash }}"

- name: Set reformatted fact
  set_fact:
    ignition_json: "{{ ignition_json | combine(passwd_object) }}"
    ignition_overrides: "{{ ignition_overrides | combine(passwd_object) }}"

- name: Set the patch data
  set_fact:
    override_ic_pass_body: "{ \"ignition_config_override\": '{{ ignition_overrides | to_json }}' }"

- name: Patch the modified Discovery Ignition Config
  uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
    return_content: yes
    method: PATCH
    body:  '{{ override_ic_pass_body }}'
    status_code: 201
    body_format: json
  register: infraenv_discovery_ign_patch
