---

- name: Template for good measure
  ansible.builtin.template:
    src: ignition-config-override-files.json.j2
    dest: "{{ generated_asset_directory }}/{{ cluster_id }}/ico-files.json"
    mode: 0644
  vars:
    ignition_version: "3.1.0"

- name: Set the patch data
  ansible.builtin.set_fact:
    override_ic_body: "{ \"ignition_config_override\": '{{ lookup(\"template\", \"ignition-config-override-files.json.j2\") | to_json }}' }"
  vars:
    ignition_version: "3.1.0"

- name: Patch the ignition_config_override_bundle_string
  ansible.builtin.uri:
    headers: "{{ compiled_uri_headers }}"
    url: "{{ assisted_service_endpoint }}/infra-envs/{{ infraenv_id }}"
    return_content: true
    method: PATCH
    body: '{{ override_ic_body }}'
    status_code: 201
    body_format: json
  register: patch_ignition_config_overrides_resp

#- name: Debug patch_ignition_config_overrides_resp
#  ansible.builtin.debug:
#    msg: "{{ patch_ignition_config_overrides_resp }}"
