---
- name: Run old fasioned oc CLI commands
  tags:
    - extra_roles
  block:
    - name: Log into the cluster
      when: cluster_kubeadmin_password is defined
      ansible.builtin.shell:
        cmd: "{{ oc_binary }} login {{ cluster_api_url }} --password=\"{{ cluster_kubeadmin_password }}\" --username=\"{{ cluster_kubeadmin_username }}\" --insecure-skip-tls-verify=true"
      environment:
        KUBECONFIG: "{{ active_kc }}"
      no_log: true
      register: cluster_auth_status
      until: (cluster_auth_status.rc == 0)
      retries: 120
      delay: 20
      tags:
        - skip_ansible_lint # We need to do this in the shell in order for it to set the context properly...pretty sure about that anyway

    - name: Deploy Extra Defined Roles
      when: extra_roles is defined
      ansible.builtin.include_role:
        name: "{{ role_name }}"
      loop: "{{ extra_roles }}"
      loop_control:
        loop_var: role_name

#  always:
#    - name: Log out of the cluster
#      ansible.builtin.shell:
#        cmd: "{{ oc_binary }} logout"
#      environment:
#        KUBECONFIG: "{{ active_kc }}"
#      changed_when: false
