name: ansible-lint Repo
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'example_vars/**'
      - 'hack/**'

  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'example_vars/**'
      - 'hack/**'

jobs:
  lint:
    name: Ansible Lint Repo # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Run ansible-lint on tasks
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible/ansible-lint-action@main
