---

#######################################################################################################################
## OpenShift Assisted Installer Service proxy configuration
#######################################################################################################################
# optional: if you need to use an outbound proxy for the cluster
cluster_proxy:
  httpProxy: http://192.168.42.31:3128/
  httpsProxy: http://192.168.42.31:3128/
  noProxy:
  - 192.168.0.0/16
  - .kemo.network
  - .kemo.labs
